### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by landsman** [cosmicwheels/jquery-checkradios#8]
Hi,

what about label?
I am often use checkboxes with this syntax:

<label><input type="checkbox"> yes i agree with rules</label>

for better user-friendly use.
Can you add support for labels?

Thanks!

EDIT: I was create simple jQuery and it works:

$("label").click(function() {
        $(this).find(".checkradios-checkbox").toggleClass("checkradios icon-checkradios-checkmark checked");
 });

**Comment by mkrauss** [comment]
Hi,

I'm not sure if the original author is following this anymore. I made a fork to rewrite the Javascript to better work with third-party code a while back and put in a pull request, but there has been no comment on that.

If what you mean by "support for labels" is that when the user clicks on a label it will focus the checkbox, my fork does fix that, along with some other issues. See the pull request here, or https://github.com/mkrauss/jquery-checkradios.

**Comment by Studioartcz** [comment]
I am working with bootstrap now. It´s only about css.
